version: "3.9"

services:
  timescale:
    image: timescale/timescaledb:latest-pg14
    container_name: spacenode-timescale
    restart: always
    environment:
      POSTGRES_PASSWORD: spacenode123
      POSTGRES_USER: spacenode
      POSTGRES_DB: spacenodedb
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: spacenode-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@spacenode.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - timescale

  emqx:
    image: emqx/emqx:latest
    container_name: spacenode-emqx
    restart: always
    environment:
      EMQX_DASHBOARD__DEFAULT_PASSWORD: ${EMQX_DASHBOARD__DEFAULT_USER__PASSWORD}
    ports:
      - "1883:1883"    # MQTT
      - "18083:18083"  # Dashboard EMQX

volumes:
  timescale_data:
